"""initial complete schema

Revision ID: a8b4ebe5fe17
Revises: 
Create Date: 2026-02-03 22:21:18.769663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b4ebe5fe17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_logs',
    sa.Column('backup_id', sa.Integer(), nullable=False),
    sa.Column('backup_type', sa.String(length=50), nullable=True),
    sa.Column('backup_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('backup_id')
    )
    op.create_table('branches',
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('branch_code', sa.String(length=10), nullable=False),
    sa.Column('branch_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('branch_id'),
    sa.UniqueConstraint('branch_code')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('cie_config',
    sa.Column('cie_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('cie_number', sa.Integer(), nullable=False),
    sa.Column('max_marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.PrimaryKeyConstraint('cie_id'),
    sa.UniqueConstraint('branch_id', 'cie_number', name='unique_branch_cie')
    )
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.String(length=20), nullable=False),
    sa.Column('academic_year', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('batches',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('batch_name', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('cie_papers',
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('paper_id')
    )
    op.create_table('staff_allocations',
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('allocated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('register_no', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.branch_id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], ),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('register_no')
    )
    op.create_table('attendance',
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT'), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('attendance_id'),
    sa.UniqueConstraint('student_id', 'date', name='unique_student_date')
    )
    op.create_table('cie_marks',
    sa.Column('cie_mark_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('cie_id', sa.Integer(), nullable=False),
    sa.Column('marks_obtained', sa.Integer(), nullable=False),
    sa.Column('entered_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cie_id'], ['cie_config.cie_id'], ),
    sa.ForeignKeyConstraint(['entered_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('cie_mark_id'),
    sa.UniqueConstraint('student_id', 'cie_id', name='unique_student_cie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cie_marks')
    op.drop_table('attendance')
    op.drop_table('students')
    op.drop_table('staff_allocations')
    op.drop_table('cie_papers')
    op.drop_table('batches')
    op.drop_table('users')
    op.drop_table('classes')
    op.drop_table('cie_config')
    op.drop_table('roles')
    op.drop_table('branches')
    op.drop_table('backup_logs')
    # ### end Alembic commands ###
